#' Run Simplex
#' Function to simulate data, sample data at some frequency, and
#' apply simplex methods to evaluate predictive ability

#' @param ctl_in Generated by mtheory_ctl function
#' @param ncores Number of cores

#' @export

run_simplex <- function(ctl_in, ncores = 6){

  #----------------------------------------------
  #Create filename for looking up
  timez <- paste0("times_", paste(range(ctl_in$times), collapse = "_"))
  seedz <- paste0("seed", ctl_in$seed)
  statez <- paste0("state", paste(ctl_in$state, collapse = "_"))
  sampz <- paste0('nsamples', ctl_in$nsamples)
  filename <- paste0("dat_", timez, "_", seedz, "_", statez, "_",
    sampz, ".Rdata")
  
  #----------------------------------------------
  #Generate data if not already present
  if(length(grep(filename, list.files("output"))) == 0){
    samps <- generate_data(seed = ctl_in$seed, nsamples = ctl_in$nsamples,
      state = ctl_in$state, times = ctl_in$times, ncores = ncores)
  }

  #If present just load the data
  if(length(grep(filename, list.files("output"))) != 0){
    load(paste0('output//', filename))
    samps <- outs
    rm(outs)  
  }
  # filename <- paste0("output//", filename)
# browser()
  #----------------------------------------------
  #sample data at some frequency
  sample_ts <- sample_data(data_in = samps, samp_freq = ctl_in$samp_freq)

  #----------------------------------------------
  #apply simplex methods
  simplex_list <- apply_simplex_list(E = ctl_in$E, lib = ctl_in$lib, 
    pred = ctl_in$pred, samp_ts = sample_ts)

#----------------------------------------------
#TO DO: Add in test of nonlinearity

  #----------------------------------------------
  return(simplex_list)
}
