#' Run Simplex
#' Function to simulate data, sample data at some frequency, and
#' apply simplex methods to evaluate predictive ability

#' @param ctl_in Generated by mtheory_ctl function
#' @param ncores Number of cores

#' @export

run_simplex <- function(ctl_in, ncores = 6){
  
  samps <- load_dat(ctl_in, ncores = ncores)

  #----------------------------------------------
  #sample data at some frequency
  sample_ts <- sample_data(data_in = samps, samp_freq = ctl_in$samp_freq)

  #----------------------------------------------
  #apply simplex methods
  simplex_list <- apply_simplex_list(E = ctl_in$E, lib = ctl_in$lib, 
    pred = ctl_in$pred, samp_ts = sample_ts)
  simplex_df <- ldply(simplex_list)
  names(simplex_df)[1] <- "iter"

  #Order the iterations
  simplex_df$iter <- as.numeric(simplex_df$iter)
  simplex_df <- simplex_df[order(simplex_df$iter), ] 

  return(simplex_df)

#----------------------------------------------
#TO DO: Add in test of nonlinearity

  #----------------------------------------------
}
